apiVersion: apps/v1
kind: Deployment
metadata:
  name: smart-irrigation-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: smart-irrigation-dev
  template:
    metadata:
      labels:
        app: smart-irrigation-dev
    spec:
      containers:
        - name: smart-irrigation-dev
          image: registry.home.olirowan.com/library/olirowan/smart-irrigation:v0.1
          env:
            - name: SESSION_TYPE
              value: "redis"
            - name: SESSION_REDIS
              value: "redis://192.168.1.112:6379/1"
            - name: CELERY_RESULT_BACKEND
              value: "redis://192.168.1.112:6379/0"
            - name: CELERY_BROKER_URL
              value: "redis://192.168.1.112:6379/0"
            - name: SQLALCHEMY_DATABASE_URI
              value: "mysql://smartirrigation:changeme@192.168.1.112:3306/smartirrigation"
