image: python:3.8-slim-buster

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
  - python -V
  - pip install virtualenv
  - virtualenv venv
  - source venv/bin/activate

stages:
  - build
  - bundle

install_dependencies:
  stage: build
  script:
    - pip install -r requirements.txt

bundle_application:
  stage: bundle
  script:
    - touch smart-irrigation.tar.gz && tar --exclude smart-irrigation.tar.gz --exclude-vcs -czvf smart-irrigation.tar.gz .
    - echo "`ls -lh ./*.tar.gz`"
