image: python:3.8-slim-buster

stages:
  - build
  - bundle

install_dependencies:
  stage: build
  script:
    - pip install -r requirements.txt

bundle_application:
  stage: bundle
  script:
    - touch smart-irrigation.tar.gz && tar --exclude smart-irrigation.tar.gz --exclude-vcs -czvf smart-irrigation.tar.gz .
    - echo "`ls -lh ./*.tar.gz"
