"""empty message

Revision ID: 0aa188a371e9
Revises: 0c6eb0b2928c
Create Date: 2021-06-08 18:05:10.125706

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0aa188a371e9'
down_revision = '0c6eb0b2928c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Watering', sa.Column('adhoc_request', sa.String(), nullable=True))
    op.add_column('Watering', sa.Column('status', sa.String(), nullable=True))
    op.add_column('Watering', sa.Column('water_end_time', sa.DateTime(), nullable=True))
    op.add_column('Watering', sa.Column('water_start_time', sa.DateTime(), nullable=True))
    op.drop_column('Watering', 'watered_at')
    op.drop_column('Watering', 'if_cancelled')
    op.drop_column('Watering', 'if_scheduled_water')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Watering', sa.Column('if_scheduled_water', sa.VARCHAR(), nullable=True))
    op.add_column('Watering', sa.Column('if_cancelled', sa.VARCHAR(), nullable=True))
    op.add_column('Watering', sa.Column('watered_at', sa.VARCHAR(), nullable=True))
    op.drop_column('Watering', 'water_start_time')
    op.drop_column('Watering', 'water_end_time')
    op.drop_column('Watering', 'status')
    op.drop_column('Watering', 'adhoc_request')
    # ### end Alembic commands ###
