"""empty message

Revision ID: 0c6eb0b2928c
Revises: d072c808d517
Create Date: 2021-05-25 18:20:25.406195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c6eb0b2928c'
down_revision = 'd072c808d517'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('watering_start_at', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'watering_start_at')
    # ### end Alembic commands ###
