"""empty message

Revision ID: 478460dded83
Revises: fc5ed6c744b8
Create Date: 2021-05-02 16:37:15.396145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478460dded83'
down_revision = 'fc5ed6c744b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('schedule_watering', sa.String(32), nullable=True))
    op.add_column('User', sa.Column('skip_rained_today', sa.String(32), nullable=True))
    op.add_column('User', sa.Column('skip_rained_yesterday', sa.String(32), nullable=True))
    op.add_column('User', sa.Column('water_duration_minutes', sa.String(32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'water_duration_minutes')
    op.drop_column('User', 'skip_rained_yesterday')
    op.drop_column('User', 'skip_rained_today')
    op.drop_column('User', 'schedule_watering')
    # ### end Alembic commands ###
