"""empty message

Revision ID: 679ca67fd380
Revises: 
Create Date: 2022-06-20 19:36:19.317627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '679ca67fd380'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=True),
    sa.Column('description', sa.String(length=128), nullable=True),
    sa.Column('watering_start_at', sa.String(length=32), nullable=True),
    sa.Column('water_duration_minutes', sa.String(length=32), nullable=True),
    sa.Column('latitude', sa.String(length=32), nullable=True),
    sa.Column('longitude', sa.String(length=32), nullable=True),
    sa.Column('owm_apikey', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=128), nullable=True),
    sa.Column('schedule_watering', sa.String(length=32), nullable=True),
    sa.Column('skip_rained_today', sa.String(length=32), nullable=True),
    sa.Column('skip_rained_yesterday', sa.String(length=32), nullable=True),
    sa.Column('skip_watered_today', sa.String(length=32), nullable=True),
    sa.Column('skip_watered_yesterday', sa.String(length=32), nullable=True),
    sa.Column('telegram_token', sa.String(length=128), nullable=True),
    sa.Column('telegram_chat_id', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Watering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_start_time', sa.DateTime(), nullable=True),
    sa.Column('water_end_time', sa.DateTime(), nullable=True),
    sa.Column('water_duration_minutes', sa.String(length=32), nullable=True),
    sa.Column('adhoc_request', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('email', sa.String(length=128), nullable=True),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('first_name', sa.String(length=32), nullable=True),
    sa.Column('last_name', sa.String(length=32), nullable=True),
    sa.Column('profileimage', sa.String(length=256), nullable=True),
    sa.Column('city', sa.String(length=32), nullable=True),
    sa.Column('country', sa.String(length=32), nullable=True),
    sa.Column('timezone', sa.String(length=128), nullable=True),
    sa.Column('primary_profile_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['primary_profile_id'], ['Settings.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    op.drop_table('Watering')
    op.drop_table('Settings')
    # ### end Alembic commands ###
