"""empty message

Revision ID: bb4564f390bf
Revises: 478460dded83
Create Date: 2021-05-17 18:46:30.341259

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb4564f390bf'
down_revision = '478460dded83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('skip_watered_today', sa.String(), nullable=True))
    op.add_column('User', sa.Column('skip_watered_yesterday', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('User', 'skip_watered_yesterday')
    op.drop_column('User', 'skip_watered_today')
    # ### end Alembic commands ###
