"""empty message

Revision ID: d072c808d517
Revises: 2235243aadff
Create Date: 2021-05-21 00:41:46.158655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd072c808d517'
down_revision = '2235243aadff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Watering',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('water_duration_minutes', sa.String(), nullable=True),
    sa.Column('if_scheduled_water', sa.String(), nullable=True),
    sa.Column('if_cancelled', sa.String(), nullable=True),
    sa.Column('watered_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_column('User', 'last_rained')
    op.drop_column('User', 'last_watered')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('last_watered', sa.VARCHAR(), nullable=True))
    op.add_column('User', sa.Column('last_rained', sa.VARCHAR(), nullable=True))
    op.drop_table('Watering')
    # ### end Alembic commands ###
