"""empty message

Revision ID: fc5ed6c744b8
Revises: 
Create Date: 2021-03-27 16:55:16.034600

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fc5ed6c744b8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(32), nullable=True),
    sa.Column('email', sa.String(128), nullable=True),
    sa.Column('password', sa.Binary(), nullable=True),
    sa.Column('first_name', sa.String(32), nullable=True),
    sa.Column('last_name', sa.String(32), nullable=True),
    sa.Column('city', sa.String(32), nullable=True),
    sa.Column('country', sa.String(32), nullable=True),
    sa.Column('timezone', sa.String(128), nullable=True),
    sa.Column('latitude', sa.String(32), nullable=True),
    sa.Column('longitude', sa.String(32), nullable=True),
    sa.Column('owm_apikey', sa.String(128), nullable=True),
    sa.Column('profileimage', sa.String(128), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('User')
    # ### end Alembic commands ###
